### ISSUE TITLE
[Suggestion] Plotinus as Synapse addon

### ISSUE THREAD

**Issue by lf-araujo** [p-e-w/plotinus#10]
THANK YOU! Your little app has been sorely needed in Gtk environments! And it is written in Vala! It's a dream, god!

One thing that I always had in mind is that this kind of functionality would fit very well as a Synapse extension. One would find files and the apps menus within the same launcher (Synapse even has this unused command tab in it!)

Anyways, your app is already excellent. This is just a suggestion for future development!

Many thanks again!

**Comment by p-e-w** [comment]
Interesting idea and thank you for the compliment! 😃

Is the Synapse plugin API documented somewhere? The Synapse Wiki is currently down...

**Comment by lf-araujo** [comment]
Unfortunately it is not, and the development is very slow (perhaps
stalled?). The best way to get used to their API is via the code of the
extant plugins here:

https://bazaar.launchpad.net/~synapse-core/synapse-project/trunk/files/head:/src/plugins/

2017-01-22 2:49 GMT+11:00 Philipp Emanuel Weidmann <notifications@github.com

**Comment by p-e-w** [comment]
Wiki is still down, and judging from the Launchpad page the project is almost dead. So on second thought, this is not something that I intend to implement.
