### ISSUE TITLE
Doesn't work with GIMP (GTK3)

### ISSUE THREAD

**Issue by ElectricPrism** [p-e-w/plotinus#11]
I'm using Gimp GTK3 from AUR
https://aur.archlinux.org/packages/gimp-gtk3-git/

Ctrl + Shift + P doesn't bring up the menu like in other apps, does anyone know why and how to fix this?

**Comment by vhaarr** [comment]
I cross posted it here https://bugzilla.gnome.org/show_bug.cgi?id=777542

**Comment by vhaarr** [comment]
So the GIMP developer in that bug pointed me to GIMPs "menu search" feature, which is basically the same thing.

The standard shortcut on linux seems to be /.

I can't believe I've used GIMP all this time and never known about it.

**Comment by ElectricPrism** [comment]
@vhaarr Thanks for investigating and requesting, I personally would probably still prefer plotinus search to their default search for consistency across gnome.

I also was unaware of the search feature - it seems like such a high-demand feature to be quietly hidden away - at the very least it deserves some sort of search button somewhere in the UX in my opinion.

For now I've rebound the / key to Ctrl + Shift + P - I'm not sure if they're going to implement GtkApplication - but at least we could put in a work communicating demand for it unless we start cloning their repository and start fiddling around until a patch presents itself.

I know the feeling - I recently learned you can drag & drop pictures into the Gnome Background dialog to add them and was completly awestruck that I never thought of doing that.

Gimp GTK3 may not be reccomended however it seems at least a dozen users over on Arch are already using it so I think inqueries on it are completly valid.

Great work, even if not immediately lets hope it gets in.

**Comment by vhaarr** [comment]
It does seem the GIMP guys have been quite outgoing in trying to stop people from packaging their GTK3 branch, at least judging by the comments here https://github.com/flatpak/flatpak/issues/279

If you read it in detail you'll see that the GTK3 branch has had 2 actual commits in a year, the other commits are just the gitweb interface misrepresenting rebases.

I disagree that the builtin functionality was "quietly hidden"; it was a toplevel item in the Help menu - I've just never looked at the Help menu or contents, which goes to show how easily I can use the GIMP, and is quite a favorable thing.

But I also agree that the plotinus interface is superior, so hopefully someone (tm) will do something (tm) :-P

**Comment by p-e-w** [comment]
> I'm not sure if they're going to implement GtkApplication

So GIMP, literally the application that GTK+ was originally written for, does *not* use GtkApplication?!? This sucks...

If true, this would make it the same issue as #7. An alternative to binding keys via GtkApplication might be to use [keybinder](https://github.com/engla/keybinder), which I actually experimented with at the beginning. However, that approach has its own problems, notably requiring IPC as there can be multiple GTK+ apps, each with its own instance of Plotinus, but only one global keybinding.

**Comment by ElectricPrism** [comment]
@p-e-w - Correct, GIMP, an app so close to GTK that GTK originally was named the Gimp Tool Kit as far as I recall isn't yet GTK 3.x when GTK 4.x is just around the corner and they don't use GtkApplication apparantly.

**Comment by p-e-w** [comment]
This should now be fixed! 🎉
