### ISSUE TITLE
Support start-of-word characters nonspaced

### ISSUE THREAD

**Issue by vhaarr** [p-e-w/plotinus#12]
Okay so this just blew my mind, and I love you.

Some time ago I changed from using Atom/Sublime to the stripped down vscode from Microsoft. Because the filesystem search in vscode is fantastic. The reason I mention it is because I don't remember how C-S-p behaves in atom/sublime.

But, in vscode, you can type for example "aca" and it will match the action "Add Cursor Above", based on the first letter of each word. I find myself using this method exclusively, and I was hoping you might consider it for plotinus.

I can't foresee with immediate clarity any way in which it would conflict with existing usage, but I'm not going to claim that it won't.

Thanks for reading!

**Comment by vhaarr** [comment]
Also worth mentioning that it will match, for example "This Sentence Matches The First Two and the Last Word" to "tsw".

**Comment by p-e-w** [comment]
Thanks for the flowers! 😊

I'm aware that this is what Sublime and its offspring do, but to be honest I've always found this to be the weirdest aspect of their command palettes. I guess I just don't think of commands in terms of their acronyms, and I remember seeing an "unintentional acronyms" bug somewhere on the Atom issue tracker, which they worked around by complicating their sort heuristics.

Overall I'm a bit on the fence with this one, but I'll consider it as a future addition.

**Comment by p-e-w** [comment]
I'm closing this as "won't fix" as I have realized I just don't want this behavior in Plotinus. Typing "file" should ***not*** match "Find In Line (Extended)".
