### ISSUE TITLE
Does not open in WINE (gtk3)

### ISSUE THREAD

**Issue by ElectricPrism** [p-e-w/plotinus#13]
Wine Applications using Staging feature doesn't seem to work, I wanted to bring it to the attention of development as I think WINE apps would stand to be a single class of many apps that could benefit.

**Comment by p-e-w** [comment]
Could you provide concrete steps for reproducing this with a simple application in Wine?

**Comment by p-e-w** [comment]
Reading a bit more about this, it appears that this feature of Wine is nothing more than a theme designed to emulate the GTK+ theme used. If that is indeed the case, there is no bug here.

**Comment by GNOME-IS-LIFE** [comment]
@ElectricPrism this is no bug. Wine simply uses the gtk3 theme. the actual inner working of wine apps are those garbage .NET Windows apps, which don't support the gnome DBus stuff, hence no Plotinus

**Comment by p-e-w** [comment]
Closing as invalid.
