### ISSUE TITLE
Support QT apps?

### ISSUE THREAD

**Issue by nsrosenqvist** [p-e-w/plotinus#15]
Are there plans to support QT menus at some stage as well? I figured that with the new support for Global Menu Bars in Plasma it could be used as a reference for how to import the menu items into Plotinus. See https://apachelog.wordpress.com/2017/02/02/how-to-global-menu-in-plasma-5-9/

**Comment by p-e-w** [comment]
I have no plans to support Qt, sorry. 😞

**Comment by satai** [comment]
Does the "no" mean "I don't want to do it myself but I can accept reasonably polished patch" or "NO, NO, NO"? ;-)

**Comment by p-e-w** [comment]
@satai: I honestly don't see how it would even be possible to support Qt short of rewriting all of Plotinus for Qt.

"Integrating" Qt support into Plotinus would involve Qt dependencies, and that is indeed something for which I would not even accept a patch. If someone wants to make a Plotinus clone/analogue for Qt though, they certainly have my blessing.
