### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by umpirsky** [p-e-w/plotinus#19]
Tried to install it on Ubuntu 16.04 with `sudo apt-get install git cmake valac libgtk-3-dev`. It went well.

Then tried to find `libplotinus.so` with `locate libplotinus.so`, but nothing found.

Any idea why is it missing?

**Comment by AlexanderMB** [comment]
Did you build and install it? libplotinus is not installed by the command `sudo apt-get install git cmake valac libgtk-3-dev`. You need to:
```
git clone https://github.com/p-e-w/plotinus.git
cd plotinus
mkdir build
cd build
cmake ..
make
```

**Comment by umpirsky** [comment]
Oh, ok, I missed that. Works now. Thanks!
