### ISSUE TITLE
doesn't work with Pantheon-Files

### ISSUE THREAD

**Issue by sgpthomas** [p-e-w/plotinus#2]
When running this with pantheon-files, nothing pops up and in the terminal, `[FATAL 15:18:37.157163] [GLib] g_strsplit: assertion 'string != NULL' failed` is displayed.

**Comment by p-e-w** [comment]
While I can't reproduce this, I have found a potential problem in the code and pushed a fix. Could you try whether this change resolves the issue for you?

**Comment by sgpthomas** [comment]
yep. it seems to work now. Although it doesn't detect very many things. Although that might be a different issue. It only shows "previous" which doesn't actually work. Let me know if I should file a separate issue about this.

**Comment by p-e-w** [comment]
I have made several improvements to command extraction after debugging some Elementary applications. Plotinus should now find many more commands than before.
