### ISSUE TITLE
Option to prevent destroying the window when focus is lost

### ISSUE THREAD

**Issue by CraftedCart** [p-e-w/plotinus#21]
When the Plotinus window loses focus, it usually destroys the window. This is particulary irritating seeing as I have my WM configured to focus where the mouse is, so if the mouse doesn't happen to be over the Plotinus window, it sometimes gets destroyed immediately.

If you are interested if merging my changes, I submitted PR #22. I did notice you said you would prefer filing an issue first, but seeing as I added some code, I submitted the PR anyway. I added the option of setting the environment variable `PLOTINUS_UNFOCUSED_PREVENT_CLOSE` to `true` to prevent this default behaviour.

**Comment by p-e-w** [comment]
Thank you for pointing this out!

As of https://github.com/p-e-w/plotinus/commit/d52b395cfa35d9e7336b4068fce8ef646f67f573, the popup window is no longer destroyed when it loses focus, so this is not an issue anymore.

**Comment by CraftedCart** [comment]
Ah ok - Thanks :)
