### ISSUE TITLE
Theming not quite right with in elementary OS

### ISSUE THREAD

**Issue by sgpthomas** [p-e-w/plotinus#3]
![wonky_theme](https://cloud.githubusercontent.com/assets/3752122/20248571/efa4d3f6-a9b4-11e6-9346-8d6086ba46e1.png)

**Comment by p-e-w** [comment]
Plotinus already tries to adapt to the theme by using for the command path (first column) the theme's foreground color at 40% alpha and for the accelerators (last column) the theme's selection background color.

That text in both these columns is invisible leads me to believe the Elementary theme might not define those colors at all. Further investigation is needed here.

The other issue is the missing margin around the search entry in the header bar. I had assumed at least some margin must be present in all themes, else apps like Nautilus would look really weird (path bar).

**Comment by p-e-w** [comment]
All theming issues in elementary that I could find have now been fixed.
