### ISSUE TITLE
Uninstalling Plotinus

### ISSUE THREAD

**Issue by lokesh-krishna** [p-e-w/plotinus#31]
What's the recommended procedure to uninstall Plotinus?
Running `sudo make uninstall` from the `build` directory gives the following output:  

    make: *** No rule to make target 'uninstall'.  Stop.

**Comment by p-e-w** [comment]
`sudo make install` installs 3 files: `libplotinus.so` (the GTK+ module), `plotinus` (the D-Bus service), and `com.worldwidemann.plotinus.gschema.xml` (the GSettings schema). If you delete these files, Plotinus is gone. The paths to these files should be in the output of `sudo make install`.
