### ISSUE TITLE
Installed but not launching

### ISSUE THREAD

**Issue by philippgovernale** [p-e-w/plotinus#33]
I have followed build and install instructions and according to output it seems to have installed successfully. But, when i try to run an application with pallete, eg nautilus by running:
`GTK3_MODULES=usr/local/lib/libplotinus.so nautilus`

the application launches, but ctrl+shift+p does not bring up the pallete

I have also added `GTK3_MODULES=/usr/local/lib/libplotinus.so` to /etc/environment

I feel like I have missed a step but I can't find the issue. I am running Fedora 27.

**Comment by p-e-w** [comment]
Looks like you are missing a leading slash: `usr/local/...` -> `/usr/local/...`.

**Comment by philippgovernale** [comment]
Thanks for your response!

Unfortunately my Fedora installation has broken :( so I can't tell you whether it's working or not. In either case the missing slash should help! I'll get back to you when I've got everything working again.

**Comment by philippgovernale** [comment]
It's definately working on another Fedora Workstation, so thank you for your patience.

**Comment by p-e-w** [comment]
Great to hear, closing this then!
