### ISSUE TITLE
Cannot Run Plotinus

### ISSUE THREAD

**Issue by utkuturk** [p-e-w/plotinus#38]
Hey, 

I use ubuntu 17.10. I followed the installation guide you provided. After installation I ran the command `sudo nano /etc/environment`. I added the full path lab as this: `GTK3_MODULES=["/usr/local/lib/libplotinus.so']` I tried without brackets too. then I enabled it with default. I edited the hotkeys to Control+Shift+P.  and I checked all of this in dconf-editor too. But  I cannot make it run.  And In dconf-editor, it says No Schema Found for plotinus. 

I really miss HUD, and this would be so helpful. Thanks a lot!

**Comment by TLogiviere** [comment]
Hello,
The syntax of your GTK3_MODULES line does not seems right. You open with double quote but close with one. Also, square brackets seems superfluous.
Here it is working after a reboot (not using ubuntu but as it now uses gnome, it should be quite similar) with the following setup:
 - /etc/environment
`GTK3_MODULES=/usr/local/lib/libplotinus.so`
- Also double check the syntax of the dconf key, it should be formatted like that (with square brackets and single quotes):
`/com/worldwidemann/plotinus/default/hotkeys ['<Super>F3']`

**Comment by utkuturk** [comment]
Thanks a lot! It works now.
