### ISSUE TITLE
DBus service not found

### ISSUE THREAD

**Issue by Naheel-Azawy** [p-e-w/plotinus#47]
Plotinus works pretty well for me for normal usage on gtk programs. But dbus fails to find it.

```python
> from pydbus import SessionBus
> bus = SessionBus()
> plotinus = bus.get("com.worldwidemann.plotinus")
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.worldwidemann.plotinus was not provided by any .service files (2)
```

Also, to be clear,

```sh
~> gsettings get com.worldwidemann.plotinus:/com/worldwidemann/plotinus/default/ dbus-enabled
true
~> echo $GTK_MODULES
xapp-gtk3-module:unity-gtk-module:appmenu-gtk-module:/usr/local/lib/libplotinus.so
```

Am I doing something wrong?

**Comment by p-e-w** [comment]
Did you start the D-Bus service, as described in the README?

**Comment by Naheel-Azawy** [comment]
Oh dude that's awkward.. I'm not sure what was wrong when I tried last time but I guess I didn't run `plotinus`. Sorry for the noise. Anyway, great work done here I really appreciate it. Have a nice day!
