### ISSUE TITLE
Make original names (before translation) searchable

### ISSUE THREAD

**Issue by jplatte** [p-e-w/plotinus#8]
Just an idea, but it would be nice if I could search for English action names within an application even if the UI is translated. I have everything set to German locally, potentially I should just change that, but in some cases it's nice to have the UI in German while I don't really need the English UI otherwise. But when searching for an action, typing Umlauts often (for common functions such as open / öffnen) is a bit annoying, even with a German keyboard.

**Comment by p-e-w** [comment]
I don't intend to implement this. The idea is that Plotinus makes what you see in the UI searchable. If the UI is translated, Plotinus will search the translated strings. Anything else would make that simple idea suddenly a lot more complex.

I might expand the search itself to be more fuzzy at some point. This could include things like making "u" match "ü" or similar.
