### ISSUE TITLE
Keyboard shortcut conflicts with existing functionality for major web browsers (Chrome/Chromium + Firefox)

### ISSUE THREAD

**Issue by Pointedstick** [p-e-w/plotinus#9]
`ctrl-shift-p` is used for `print` in Chrome/Chromium. And it opens a new Private Browsing window in Firefox. Might wanna change the shortcut to something more esoteric.

**Comment by mutlay** [comment]
Also conflicts in Inkscape and so long. @p-e-w, the shortcut definitely must be customizable.

**Comment by p-e-w** [comment]
Merging this into #4.

As a side note, even without the conflict none of Firefox, Chrome and Inkscape would work. Firefox uses custom (non-GTK) widgets, Inkscape is still on GTK+ 2 and Chrome has *both* these problems.
